### ISSUE TITLE
Twitching/flickering popup window

### ISSUE THREAD

**Issue by Stimmenhotel** [vantezzen/dontbugme#1]
Hey there, thanks for this nice addon.
But I have a problem ... The popup/dropdown-window is flickering/twitching a lot.
If I zoom out in this window it works better.

Here is a gif of the problem:
![problem](https://user-images.githubusercontent.com/15821524/58277990-4c004600-7d9b-11e9-8f0c-ff079f5e97f1.gif)

**Comment by vantezzen** [comment]
Thank you for reporting this issue.
It seems like the improved design from version 1.5 introduced these weird twitching errors in Firefox - which I unfortunately didn't notice. I have just published version 1.6 of the extension which should fix this issue by setting a fixed width instead of just setting a min-width for the popup.
