### ISSUE TITLE
No logins for ccTLD

### ISSUE THREAD

**Issue by clockworkgeek** [vantezzen/dontbugme#8]
DontBugMe only searches for the two highest levels of a domain. This is incorrect when dealing with country codes e.g. `example.co.uk` is shortened to `co.uk` which obviously doesn't match a real site and so gives the message "It looks like there are no logins availible for this page."

Browser is Firefox 74.
Add-on version is 1.12.

P.S. "availible" is mispelled.

**Comment by CookieCoder15** [comment]
@clockworkgeek I have attempted a solution for this problem and made a pull request. The copy in my fork works for now in debug mode and could be compiled using something such as [web-ext](https://github.com/mozilla/web-ext) for a more permanent solution until the PR is reviewed and hopefully merged.

**Comment by vantezzen** [comment]
DontBugMe 2 will have a selection for which domain should be used:

<img width="260" alt="Screenshot 2021-08-04 at 13 47 09" src="https://user-images.githubusercontent.com/10333196/128175490-0c4bbdfe-591c-4e64-9056-6fc558f2ec82.png">

This allows searching specific subdomains but also fixes this issue. DontBugMe addidionally uses the complete domain by default instead of trying to shorten it.
